# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Analogy.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import timestamp_pb2 as timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Analogy.proto',
  package='greet',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rAnalogy.proto\x12\x05greet\x1a\x0ftimestamp.proto\"\xfb\x03\n\x15\x41nalogyGRPCLogMessage\x12\x0c\n\x04Text\x18\x01 \x01(\t\x12)\n\x05Level\x18\x02 \x01(\x0e\x32\x1a.greet.AnalogyGRPCLogLevel\x12(\n\x04\x44\x61te\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tProcessId\x18\x04 \x01(\x05\x12\x10\n\x08ThreadId\x18\x05 \x01(\x05\x12\x0e\n\x06Module\x18\x06 \x01(\t\x12\x0e\n\x06Source\x18\x07 \x01(\t\x12\x12\n\nMethodName\x18\x08 \x01(\t\x12\x10\n\x08\x46ileName\x18\t \x01(\t\x12\x12\n\nLineNumber\x18\n \x01(\x05\x12\x13\n\x0bMachineName\x18\x0b \x01(\t\x12\x10\n\x08\x43\x61tegory\x18\x0c \x01(\t\x12\x0c\n\x04User\x18\r \x01(\t\x12V\n\x15\x41\x64\x64itionalInformation\x18\x0e \x03(\x0b\x32\x37.greet.AnalogyGRPCLogMessage.AdditionalInformationEntry\x12\n\n\x02Id\x18\x0f \x01(\t\x12)\n\x05\x43lass\x18\x10 \x01(\x0e\x32\x1a.greet.AnalogyGRPCLogClass\x1a<\n\x1a\x41\x64\x64itionalInformationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"&\n\x13\x41nalogyMessageReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"D\n\x16\x41nalogyConsumerMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x19\n\x11streamOldMessages\x18\x02 \x01(\x08*E\n\x13\x41nalogyGRPCLogClass\x12\x0b\n\x07GENERAL\x10\x00\x12\x0c\n\x08SECURITY\x10\x01\x12\n\n\x06HAZARD\x10\x02\x12\x07\n\x03PHI\x10\x03*\x93\x01\n\x13\x41nalogyGRPCLogLevel\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05TRACE\x10\x01\x12\x0b\n\x07VERBOSE\x10\x02\x12\t\n\x05\x44\x45\x42UG\x10\x03\x12\x0f\n\x0bINFORMATION\x10\x04\x12\x0b\n\x07WARNING\x10\x05\x12\t\n\x05\x45RROR\x10\x06\x12\x0c\n\x08\x43RITICAL\x10\x07\x12\x0b\n\x07\x41NALOGY\x10\x08\x12\x08\n\x04NONE\x10\t2\xc7\x01\n\x07\x41nalogy\x12\\\n\x1eSubscribeForPublishingMessages\x12\x1c.greet.AnalogyGRPCLogMessage\x1a\x1a.greet.AnalogyMessageReply(\x01\x12^\n\x1dSubscribeForConsumingMessages\x12\x1d.greet.AnalogyConsumerMessage\x1a\x1c.greet.AnalogyGRPCLogMessage0\x01\x62\x06proto3'
  ,
  dependencies=[timestamp__pb2.DESCRIPTOR,])

_ANALOGYGRPCLOGCLASS = _descriptor.EnumDescriptor(
  name='AnalogyGRPCLogClass',
  full_name='greet.AnalogyGRPCLogClass',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GENERAL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HAZARD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PHI', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=661,
  serialized_end=730,
)
_sym_db.RegisterEnumDescriptor(_ANALOGYGRPCLOGCLASS)

AnalogyGRPCLogClass = enum_type_wrapper.EnumTypeWrapper(_ANALOGYGRPCLOGCLASS)
_ANALOGYGRPCLOGLEVEL = _descriptor.EnumDescriptor(
  name='AnalogyGRPCLogLevel',
  full_name='greet.AnalogyGRPCLogLevel',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRACE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VERBOSE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEBUG', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INFORMATION', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CRITICAL', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ANALOGY', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NONE', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=733,
  serialized_end=880,
)
_sym_db.RegisterEnumDescriptor(_ANALOGYGRPCLOGLEVEL)

AnalogyGRPCLogLevel = enum_type_wrapper.EnumTypeWrapper(_ANALOGYGRPCLOGLEVEL)
GENERAL = 0
SECURITY = 1
HAZARD = 2
PHI = 3
UNKNOWN = 0
TRACE = 1
VERBOSE = 2
DEBUG = 3
INFORMATION = 4
WARNING = 5
ERROR = 6
CRITICAL = 7
ANALOGY = 8
NONE = 9



_ANALOGYGRPCLOGMESSAGE_ADDITIONALINFORMATIONENTRY = _descriptor.Descriptor(
  name='AdditionalInformationEntry',
  full_name='greet.AnalogyGRPCLogMessage.AdditionalInformationEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='greet.AnalogyGRPCLogMessage.AdditionalInformationEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='greet.AnalogyGRPCLogMessage.AdditionalInformationEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=489,
  serialized_end=549,
)

_ANALOGYGRPCLOGMESSAGE = _descriptor.Descriptor(
  name='AnalogyGRPCLogMessage',
  full_name='greet.AnalogyGRPCLogMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Text', full_name='greet.AnalogyGRPCLogMessage.Text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Level', full_name='greet.AnalogyGRPCLogMessage.Level', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Date', full_name='greet.AnalogyGRPCLogMessage.Date', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ProcessId', full_name='greet.AnalogyGRPCLogMessage.ProcessId', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ThreadId', full_name='greet.AnalogyGRPCLogMessage.ThreadId', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Module', full_name='greet.AnalogyGRPCLogMessage.Module', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Source', full_name='greet.AnalogyGRPCLogMessage.Source', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MethodName', full_name='greet.AnalogyGRPCLogMessage.MethodName', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FileName', full_name='greet.AnalogyGRPCLogMessage.FileName', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LineNumber', full_name='greet.AnalogyGRPCLogMessage.LineNumber', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MachineName', full_name='greet.AnalogyGRPCLogMessage.MachineName', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Category', full_name='greet.AnalogyGRPCLogMessage.Category', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='User', full_name='greet.AnalogyGRPCLogMessage.User', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AdditionalInformation', full_name='greet.AnalogyGRPCLogMessage.AdditionalInformation', index=13,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Id', full_name='greet.AnalogyGRPCLogMessage.Id', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Class', full_name='greet.AnalogyGRPCLogMessage.Class', index=15,
      number=16, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ANALOGYGRPCLOGMESSAGE_ADDITIONALINFORMATIONENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=549,
)


_ANALOGYMESSAGEREPLY = _descriptor.Descriptor(
  name='AnalogyMessageReply',
  full_name='greet.AnalogyMessageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='greet.AnalogyMessageReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=589,
)


_ANALOGYCONSUMERMESSAGE = _descriptor.Descriptor(
  name='AnalogyConsumerMessage',
  full_name='greet.AnalogyConsumerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='greet.AnalogyConsumerMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='streamOldMessages', full_name='greet.AnalogyConsumerMessage.streamOldMessages', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=591,
  serialized_end=659,
)

_ANALOGYGRPCLOGMESSAGE_ADDITIONALINFORMATIONENTRY.containing_type = _ANALOGYGRPCLOGMESSAGE
_ANALOGYGRPCLOGMESSAGE.fields_by_name['Level'].enum_type = _ANALOGYGRPCLOGLEVEL
_ANALOGYGRPCLOGMESSAGE.fields_by_name['Date'].message_type = timestamp__pb2._TIMESTAMP
_ANALOGYGRPCLOGMESSAGE.fields_by_name['AdditionalInformation'].message_type = _ANALOGYGRPCLOGMESSAGE_ADDITIONALINFORMATIONENTRY
_ANALOGYGRPCLOGMESSAGE.fields_by_name['Class'].enum_type = _ANALOGYGRPCLOGCLASS
DESCRIPTOR.message_types_by_name['AnalogyGRPCLogMessage'] = _ANALOGYGRPCLOGMESSAGE
DESCRIPTOR.message_types_by_name['AnalogyMessageReply'] = _ANALOGYMESSAGEREPLY
DESCRIPTOR.message_types_by_name['AnalogyConsumerMessage'] = _ANALOGYCONSUMERMESSAGE
DESCRIPTOR.enum_types_by_name['AnalogyGRPCLogClass'] = _ANALOGYGRPCLOGCLASS
DESCRIPTOR.enum_types_by_name['AnalogyGRPCLogLevel'] = _ANALOGYGRPCLOGLEVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnalogyGRPCLogMessage = _reflection.GeneratedProtocolMessageType('AnalogyGRPCLogMessage', (_message.Message,), {

  'AdditionalInformationEntry' : _reflection.GeneratedProtocolMessageType('AdditionalInformationEntry', (_message.Message,), {
    'DESCRIPTOR' : _ANALOGYGRPCLOGMESSAGE_ADDITIONALINFORMATIONENTRY,
    '__module__' : 'Analogy_pb2'
    # @@protoc_insertion_point(class_scope:greet.AnalogyGRPCLogMessage.AdditionalInformationEntry)
    })
  ,
  'DESCRIPTOR' : _ANALOGYGRPCLOGMESSAGE,
  '__module__' : 'Analogy_pb2'
  # @@protoc_insertion_point(class_scope:greet.AnalogyGRPCLogMessage)
  })
_sym_db.RegisterMessage(AnalogyGRPCLogMessage)
_sym_db.RegisterMessage(AnalogyGRPCLogMessage.AdditionalInformationEntry)

AnalogyMessageReply = _reflection.GeneratedProtocolMessageType('AnalogyMessageReply', (_message.Message,), {
  'DESCRIPTOR' : _ANALOGYMESSAGEREPLY,
  '__module__' : 'Analogy_pb2'
  # @@protoc_insertion_point(class_scope:greet.AnalogyMessageReply)
  })
_sym_db.RegisterMessage(AnalogyMessageReply)

AnalogyConsumerMessage = _reflection.GeneratedProtocolMessageType('AnalogyConsumerMessage', (_message.Message,), {
  'DESCRIPTOR' : _ANALOGYCONSUMERMESSAGE,
  '__module__' : 'Analogy_pb2'
  # @@protoc_insertion_point(class_scope:greet.AnalogyConsumerMessage)
  })
_sym_db.RegisterMessage(AnalogyConsumerMessage)


_ANALOGYGRPCLOGMESSAGE_ADDITIONALINFORMATIONENTRY._options = None

_ANALOGY = _descriptor.ServiceDescriptor(
  name='Analogy',
  full_name='greet.Analogy',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=883,
  serialized_end=1082,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubscribeForPublishingMessages',
    full_name='greet.Analogy.SubscribeForPublishingMessages',
    index=0,
    containing_service=None,
    input_type=_ANALOGYGRPCLOGMESSAGE,
    output_type=_ANALOGYMESSAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubscribeForConsumingMessages',
    full_name='greet.Analogy.SubscribeForConsumingMessages',
    index=1,
    containing_service=None,
    input_type=_ANALOGYCONSUMERMESSAGE,
    output_type=_ANALOGYGRPCLOGMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANALOGY)

DESCRIPTOR.services_by_name['Analogy'] = _ANALOGY

# @@protoc_insertion_point(module_scope)
