# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Analogy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import timestamp_pb2 as timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Analogy.proto',
  package='greet',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rAnalogy.proto\x12\x05greet\x1a\x0ftimestamp.proto\"\xbb\x03\n\x11\x41nalogyLogMessage\x12\n\n\x02Id\x18\x01 \x01(\t\x12(\n\x04\x44\x61te\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04Text\x18\x03 \x01(\t\x12\x10\n\x08\x43\x61tegory\x18\x04 \x01(\t\x12\x0e\n\x06Source\x18\x05 \x01(\t\x12\x12\n\nMethodName\x18\x06 \x01(\t\x12\x10\n\x08\x46ileName\x18\x07 \x01(\t\x12\x12\n\nLineNumber\x18\x08 \x01(\x05\x12\r\n\x05\x43lass\x18\t \x01(\t\x12\x13\n\x0bMachineName\x18\n \x01(\t\x12\r\n\x05Level\x18\x0b \x01(\t\x12\x0e\n\x06Module\x18\x0c \x01(\t\x12\x11\n\tProcessId\x18\r \x01(\x05\x12\x10\n\x08ThreadId\x18\x0e \x01(\x05\x12\x0c\n\x04User\x18\x0f \x01(\t\x12R\n\x15\x41\x64\x64itionalInformation\x18\x10 \x03(\x0b\x32\x33.greet.AnalogyLogMessage.AdditionalInformationEntry\x1a<\n\x1a\x41\x64\x64itionalInformationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"&\n\x13\x41nalogyMessageReply\x12\x0f\n\x07message\x18\x01 \x01(\t\")\n\x16\x41nalogyConsumerMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb7\x01\n\x07\x41nalogy\x12R\n\x18SubscribeForSendMessages\x12\x18.greet.AnalogyLogMessage\x1a\x1a.greet.AnalogyMessageReply(\x01\x12X\n\x1bSubscribeForConsumeMessages\x12\x1d.greet.AnalogyConsumerMessage\x1a\x18.greet.AnalogyLogMessage0\x01\x62\x06proto3'
  ,
  dependencies=[timestamp__pb2.DESCRIPTOR,])




_ANALOGYLOGMESSAGE_ADDITIONALINFORMATIONENTRY = _descriptor.Descriptor(
  name='AdditionalInformationEntry',
  full_name='greet.AnalogyLogMessage.AdditionalInformationEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='greet.AnalogyLogMessage.AdditionalInformationEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='greet.AnalogyLogMessage.AdditionalInformationEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=485,
)

_ANALOGYLOGMESSAGE = _descriptor.Descriptor(
  name='AnalogyLogMessage',
  full_name='greet.AnalogyLogMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='greet.AnalogyLogMessage.Id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Date', full_name='greet.AnalogyLogMessage.Date', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Text', full_name='greet.AnalogyLogMessage.Text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Category', full_name='greet.AnalogyLogMessage.Category', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Source', full_name='greet.AnalogyLogMessage.Source', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MethodName', full_name='greet.AnalogyLogMessage.MethodName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FileName', full_name='greet.AnalogyLogMessage.FileName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LineNumber', full_name='greet.AnalogyLogMessage.LineNumber', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Class', full_name='greet.AnalogyLogMessage.Class', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MachineName', full_name='greet.AnalogyLogMessage.MachineName', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Level', full_name='greet.AnalogyLogMessage.Level', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Module', full_name='greet.AnalogyLogMessage.Module', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ProcessId', full_name='greet.AnalogyLogMessage.ProcessId', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ThreadId', full_name='greet.AnalogyLogMessage.ThreadId', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='User', full_name='greet.AnalogyLogMessage.User', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AdditionalInformation', full_name='greet.AnalogyLogMessage.AdditionalInformation', index=15,
      number=16, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ANALOGYLOGMESSAGE_ADDITIONALINFORMATIONENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=485,
)


_ANALOGYMESSAGEREPLY = _descriptor.Descriptor(
  name='AnalogyMessageReply',
  full_name='greet.AnalogyMessageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='greet.AnalogyMessageReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=525,
)


_ANALOGYCONSUMERMESSAGE = _descriptor.Descriptor(
  name='AnalogyConsumerMessage',
  full_name='greet.AnalogyConsumerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='greet.AnalogyConsumerMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=568,
)

_ANALOGYLOGMESSAGE_ADDITIONALINFORMATIONENTRY.containing_type = _ANALOGYLOGMESSAGE
_ANALOGYLOGMESSAGE.fields_by_name['Date'].message_type = timestamp__pb2._TIMESTAMP
_ANALOGYLOGMESSAGE.fields_by_name['AdditionalInformation'].message_type = _ANALOGYLOGMESSAGE_ADDITIONALINFORMATIONENTRY
DESCRIPTOR.message_types_by_name['AnalogyLogMessage'] = _ANALOGYLOGMESSAGE
DESCRIPTOR.message_types_by_name['AnalogyMessageReply'] = _ANALOGYMESSAGEREPLY
DESCRIPTOR.message_types_by_name['AnalogyConsumerMessage'] = _ANALOGYCONSUMERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnalogyLogMessage = _reflection.GeneratedProtocolMessageType('AnalogyLogMessage', (_message.Message,), {

  'AdditionalInformationEntry' : _reflection.GeneratedProtocolMessageType('AdditionalInformationEntry', (_message.Message,), {
    'DESCRIPTOR' : _ANALOGYLOGMESSAGE_ADDITIONALINFORMATIONENTRY,
    '__module__' : 'Analogy_pb2'
    # @@protoc_insertion_point(class_scope:greet.AnalogyLogMessage.AdditionalInformationEntry)
    })
  ,
  'DESCRIPTOR' : _ANALOGYLOGMESSAGE,
  '__module__' : 'Analogy_pb2'
  # @@protoc_insertion_point(class_scope:greet.AnalogyLogMessage)
  })
_sym_db.RegisterMessage(AnalogyLogMessage)
_sym_db.RegisterMessage(AnalogyLogMessage.AdditionalInformationEntry)

AnalogyMessageReply = _reflection.GeneratedProtocolMessageType('AnalogyMessageReply', (_message.Message,), {
  'DESCRIPTOR' : _ANALOGYMESSAGEREPLY,
  '__module__' : 'Analogy_pb2'
  # @@protoc_insertion_point(class_scope:greet.AnalogyMessageReply)
  })
_sym_db.RegisterMessage(AnalogyMessageReply)

AnalogyConsumerMessage = _reflection.GeneratedProtocolMessageType('AnalogyConsumerMessage', (_message.Message,), {
  'DESCRIPTOR' : _ANALOGYCONSUMERMESSAGE,
  '__module__' : 'Analogy_pb2'
  # @@protoc_insertion_point(class_scope:greet.AnalogyConsumerMessage)
  })
_sym_db.RegisterMessage(AnalogyConsumerMessage)


_ANALOGYLOGMESSAGE_ADDITIONALINFORMATIONENTRY._options = None

_ANALOGY = _descriptor.ServiceDescriptor(
  name='Analogy',
  full_name='greet.Analogy',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=571,
  serialized_end=754,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubscribeForSendMessages',
    full_name='greet.Analogy.SubscribeForSendMessages',
    index=0,
    containing_service=None,
    input_type=_ANALOGYLOGMESSAGE,
    output_type=_ANALOGYMESSAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubscribeForConsumeMessages',
    full_name='greet.Analogy.SubscribeForConsumeMessages',
    index=1,
    containing_service=None,
    input_type=_ANALOGYCONSUMERMESSAGE,
    output_type=_ANALOGYLOGMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANALOGY)

DESCRIPTOR.services_by_name['Analogy'] = _ANALOGY

# @@protoc_insertion_point(module_scope)
